# All available configuration can be found here:
# https://www.algolia.com/doc/api-client/symfony/configuration/
algolia_search:
    prefix: '%env(APP_ENV)%_'
    indices:
        - name: questions
          class: App\Entity\Question
          enable_serializer_groups: true

        - name: tags
          class: App\Entity\Tag
          enable_serializer_groups: true